import ActionTree, { Action, ActionConfig } from "../ActionTree.js";



export default class RunCommand implements Action {
  constructor(
    private readonly commands: string,
  ) {}

  public async compile(config: ActionConfig): Promise<{endFunctionIndex: number}> {
    const {scene} = config;

    await ActionTree.appendAction(config, `
      # commands generated by the RunCommand Action
      ${this.commands}
    `);

    return {
      endFunctionIndex: config.functionIndex,
    }
  }
}